<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Agarwal" failures="1" tests="1" name="awesomecucumber.runners.FailedRunnerTests" time="11.086" errors="0" timestamp="2023-12-03T13:32:25 IST" skipped="0">
  <testcase classname="awesomecucumber.runners.FailedRunnerTests" name="runScenario" time="11.086">
    <failure message="Failing this step intentionally to check the screenshot attached int the Report" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this step intentionally to check the screenshot attached int the Report
at org.testng.Assert.fail(Assert.java:111)
at awesomecucumber.stepdefinitions.ProductStepDefinitions.iShouldSeeAnError(ProductStepDefinitions.java:47)
at âœ½.I should see an error(file:///C:/Workspace/Webdriver-Framework/src/test/resources/features/add_to_cart.feature:50)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- awesomecucumber.runners.FailedRunnerTests -->
